[package]
name = "gen-tpm2-cmd-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
bitflags = "1.3.2"
clap = { version = "4.0.32", features = ["derive"] }
